### ISSUE TITLE
PlatformNavBar creating multiple widgets

### ISSUE THREAD

**Issue by nicoragua** [stryder-dev/flutter_platform_widgets#204] opened 2020-07-29 09:36 UTC
Hi all,

I am currently facing an issue with the platform navigation bar when building my for iOS devices. Every time I select an item that has not yet been selected, a new widget is created and the previous ones are overwritten with the one selected.
e.g. I start on widget A so there is one A widget. I switch to B and now there are two Bs, back to A and there are two As, switch to C and now there are 3 Cs and so on.

![tempsnip](https://user-images.githubusercontent.com/32699986/88783747-7adc2e00-d18f-11ea-8352-970dbab18070.png)

I`ve created a simple test project in which i was able to recreate the bug.
https://github.com/nicoragua/navi_test

Has anyone else encountered this, or maybe knows how to fix it?

Thanks in advance :)

**Comment by aqwert** [comment] 2020-07-29 22:54
This is an issue with using `PlatformScaffold` for bottom navigation. There are 2 things you could do:

1. Remove `body` and replace with `cupertinoTabChildBuilder`

```
    return PlatformScaffold(
      cupertinoTabChildBuilder: (_, index) => _getRoute(index),
      bottomNavBar: PlatformNavBar(
        currentIndex: _index,
        itemChanged: (index) => {_changeIndex(index)},
        items: [
          _getItem(Icons.looks_one, "eins"),
          _getItem(Icons.looks_two, "zwei"),
          _getItem(Icons.looks_3, "drei"),
        ],
      ),
    );
```

2. Use `PlatformTabScaffold` (Preferred as this gives more control of the index without needing to track it yourself)

```
 return PlatformTabScaffold(
      bodyBuilder: (context, index) => _getRoute(index),
      items: [
        _getItem(Icons.looks_one, "eins"),
        _getItem(Icons.looks_two, "zwei"),
        _getItem(Icons.looks_3, "drei"),
      ],
    );
```

**Comment by Atteprojects** [comment] 2020-08-13 05:55
Hello, I am facing the same issue and I tried both methods mentioned above but it did not really fix anything and the problem is only on ios

**Comment by aqwert** [comment] 2020-08-13 21:31
@Atteprojects Could you provide a sample? My testing has that when using `PlatformTabScaffold` with `bodyBuilder` it does not have this issue.

**Comment by aqwert** [comment] 2020-11-13 22:02
Closing as no more info was provided

**Closed by aqwert** 2020-11-13 22:02 UTC
