### ISSUE TITLE
why initstate() is called multiple times in stateful widget when we use platform widgets?

### ISSUE THREAD

**Issue by miroda** [stryder-dev/flutter_platform_widgets#77] opened 2019-09-06 02:31 UTC
if we combine platform widget with PlatformNavBar,after we switch from tab1 to tab2, initstate() nitstate() is called multiple times!!! Really a big issue !
`
    return PlatformNavBar(
      currentIndex: _selectedTabIndex,

      itemChanged: (int index) {
        setState(() {
          _selectedTabIndex = index;
        });
      },
      items: [
        BottomNavigationBarItem(
            icon: Icon(Icons.home),
            title: Text('home')
        ),
        BottomNavigationBarItem(
            icon: Icon(Icons.search),
            title: Text('search')
        ),
        BottomNavigationBarItem(
            icon: Icon(Icons.shopping_cart),
            title: Text('shopping_cart')
        ),

      ],
    );`

**Comment by aqwert** [comment] 2019-09-13 11:35
Possibly, you can check the `_selectedTabIndex` is different to `index`. If so you can call `setState`

**Comment by miroda** [comment] 2019-09-18 09:18
I all ready use
 `setState(() {
      _selectedTabIndex = index;
    });`
setState will not solve this problem

**Comment by nuzelac** [comment] 2019-10-13 11:40
In my app  I was sending an `IndexedStack` to `CupertinoPageScaffoldData` just like in the Material bottom navigation examples found online. I also saw `initState` called for all tabs in the stack on every tab change.

I now have a `switch`/`case` for the displayed page depending on `currentIndex` and a `CupertinoTabView` based on the [docs](https://pub.dev/documentation/base/latest/flutter_cupertino_tab_scaffold/CupertinoTabScaffold-class.html): 
https://github.com/nuzelac/flutter_platform_widgets/commit/40397c7d2d464a3abcde085d4a5abe825e7e7750#diff-9e8b88c4d09d55248fb07d203c54a3e3

Don't know if there is a better approach.

**Comment by aqwert** [comment] 2019-10-13 22:13
That could be a solution. I will need to test it.

**Comment by binaverse** [comment] 2019-10-24 20:03
Experiencing this issue as well, tried both IndexedStack, PageStorage to preserve tab state and I still get initState firing multiple times. By the time I cycle through all 4 tabs, initState is fired 4 times when tab is selected.

@aqwert - really hoping you can resolve this.

@nuzelac  - can you provide more info on your implementation of the fix? I was able to resolve the initState calls, but now I cannot navigate. "Could not find a generator for route RouteSettings("/CardScreen", null) in the _CupertinoTabViewState." My route generator is already defined in PlatformApp.

**Comment by aqwert** [comment] 2019-12-12 10:05
@binaverse when you say initState is firing multiple times. Is it the page initState on the page that is firing or the widget you are using for each tab? Could you provide a working example

**Comment by aqwert** [comment] 2020-01-22 01:14
I have put together a `PlatformTabScaffold` that should be easier and better to use. Can you try that to see if the issue exists there?

**Comment by danny97101** [comment] 2020-03-29 18:46
I'm experiencing the same issue. Only on iOS initState() is firing the same number of times as different tabs that have already been displayed. has anyone found a fix for this? The Flutter Inspector shows that the widget is actually loading twice.

**Comment by aqwert** [comment] 2020-03-29 19:49
What would it look like if you used purely cupertino widgets? If the problem is not there then I can update the PlatformTabScaffold to match, or if it does exist using cupertino then that would be something to raise with flutter itself

**Comment by aqwert** [comment] 2020-05-16 09:39
https://github.com/aqwert/flutter_platform_widgets/issues/168

**Comment by aqwert** [comment] 2020-06-04 23:22
If anything this issue is a flutter issue. If an example of using flutter widgets directly works then I can see if this library needs adjusting to match. If you feel like this is not a flutter issue please reopen with an example using flutter only widgets that work

**Closed by aqwert** 2020-06-04 23:22 UTC
