### ISSUE TITLE
Navigation bar icons in wrong position on iOS

### ISSUE THREAD

**Issue by dg76** [stryder-dev/flutter_platform_widgets#131] opened 2020-01-18 12:35 UTC
Hi! Thank you for writing this library! I have a problem with the bar button items on iOS. This code

```
        PlatformAppBar(
            title: Text(widget.title),
            trailingActions: <Widget>[
              PlatformIconButton(icon: Icon(Icons.compare))
            ],
         )

```

results in the icon to be displayed shifted and too small:

![image](https://user-images.githubusercontent.com/17218461/72663755-47f1fa00-39f6-11ea-96d1-a3407adedd5a.png)

When using an iOS specific CupertinoNavigationBarData icon it works correctly:

```
          PlatformAppBar(
            title: Text(widget.title),
            trailingActions: <Widget>[
              PlatformIconButton(icon: Icon(Icons.compare))
            ],
            ios: (_) =>
                CupertinoNavigationBarData(
                  trailing: GestureDetector(
                    child: Icon(Icons.compare)),
                ),
          ),
       )

```

![image](https://user-images.githubusercontent.com/17218461/72663750-3c063800-39f6-11ea-81de-235a68776018.png)

However it should not be necessary to specify "ios", it should already work correctly with the PlatformIconButton, right? 🙂

**Comment by aqwert** [comment] 2020-01-19 09:37
In your example you are using `PlatformIconButton` which for ios uses `CupertinoButton`. This is not the same as the other example using the `GestureDetector`. 
I would argue that the `PlatformIconButton` size is correct. The position is not which is caused by the `CuoertinoButton` having a default padding of...

./flutterio/flutter/packages/flutter/lib/src/cupertino/button.dart
```
// Measured against iOS 12 in Xcode.
const EdgeInsets _kButtonPadding = EdgeInsets.all(16.0);
const EdgeInsets _kBackgroundButtonPadding = EdgeInsets.symmetric(
  vertical: 14.0,
  horizontal: 64.0,
);
```
```
                padding: widget.padding ?? (backgroundColor != null
                  ? _kBackgroundButtonPadding
                  : _kButtonPadding),
```

I suggest to set the padding to zero.

```
PlatformAppBar(
            title: Text(widget.title),
            trailingActions: <Widget>[
              PlatformIconButton(
                   icon: Icon(Icons.compare),
                  padding: EdgeInsets.all(0),
               )
            ],
         )
```

**Comment by aqwert** [comment] 2020-01-19 09:40
If you want to have it look like the second example you can use `GestureDetector` the way you have it

**Comment by dg76** [comment] 2020-01-19 12:43
Thank you very much for your quick response! With the padding set to zero it looks better but it still does not look correct:

PlatformIconButton with Icons.add:

![Screenshot 2020-01-19 at 13 33 17](https://user-images.githubusercontent.com/17218461/72681044-455bd700-3ac0-11ea-9e16-87a579807e59.png)

PlatformIconButton with CupertinoIcons.add:

![Screenshot 2020-01-19 at 13 34 25](https://user-images.githubusercontent.com/17218461/72681059-6fad9480-3ac0-11ea-8c13-674214d72b43.png)

CupertinoNavigationBarData with CupertinoIcons.add:

![Screenshot 2020-01-19 at 13 35 30](https://user-images.githubusercontent.com/17218461/72681075-9966bb80-3ac0-11ea-801c-a6be3376c648.png)

And this is how it looks in a native iOS 13 app:

![Screenshot 2020-01-19 at 13 37 48](https://user-images.githubusercontent.com/17218461/72681139-f5c9db00-3ac0-11ea-8cac-23d10d2808d7.png)

So shouldn't it at least look like "CupertinoNavigationBarData with CupertinoIcons.add" when I use "PlatformIconButton with CupertinoIcons.add"? It would still not look like a native app but that's probably something the Cupertino library developers would have to fix.

**Comment by aqwert** [comment] 2020-01-19 20:46
I guess there is a bit of an assumption on my part that the `CupertinoButton` would be the option to go for. I guess there is a case for using the `GestureDetector` instead of the `CupetinoButton`.

One question, are there any animations or splash effects when tapping a native ios nav button?

**Comment by dg76** [comment] 2020-01-20 08:28
A CupertinoNavigationBarData with a CupertinoButton looks even worse:

        ios: (_) => CupertinoNavigationBarData(
          trailing: CupertinoButton(child: Icon(CupertinoIcons.add), onPressed: () => onAddRecording(context)),
        ),

![Screenshot 2020-01-20 at 08 30 13](https://user-images.githubusercontent.com/17218461/72706801-2a8c6f80-3b5f-11ea-8bdc-022b255e10d8.png)

It is too small and moved down. :-(

There is no animation, the icon just gets faded while you press it, that's all.

So I think PlatformIconButton should use a GestureDetector with an Icon with a CupertinoIcon. And I also think that the CupertinoIcon has to be fixed (if the purpose of the Cupertino library is to clone the look of a native iOS app). I have reported that bug now here:

https://github.com/flutter/flutter/issues/49157

Thank you very much again for your quick responses! 👍

**Comment by aqwert** [comment] 2020-01-20 20:36
I will see what I can do. Thinking of having either a renderer for it or an option to use GestureDetector.

**Comment by andreacimino** [comment] 2020-01-20 22:32
In 0.31.0 everything was working fine, after the upgrade I have also this issue.

**Comment by aqwert** [comment] 2020-01-21 08:57
Looking at the flutter demos the implementation of a nav bar it uses the `CupertinoButton` with zero padding. 

https://github.com/flutter/flutter/blob/ac7b307803fc3dfdd142fd4791192adc2fdb26f2/examples/flutter_gallery/lib/gallery/demo.dart#L239

**Comment by dg76** [comment] 2020-01-21 09:26
Yes, I saw that, too. However it does not make it look more correct. CupertinoButton with zero padding:

![Simulator_Screen_Shot_-_iPhone_8_-_2020-01-21_at_10_08_40](https://user-images.githubusercontent.com/17218461/72790660-4adb2d80-3c36-11ea-98c0-3103a5db748b.png)

Just an "Icon" with GestureDetector:

![Simulator_Screen_Shot_-_iPhone_8_-_2020-01-21_at_10_11_14](https://user-images.githubusercontent.com/17218461/72790735-6c3c1980-3c36-11ea-95ac-9eae164c157e.png)

Native iOS 13 app:

![Simulator_Screen_Shot_-_iPhone_8_-_2020-01-20_at_09_15_41](https://user-images.githubusercontent.com/17218461/72790789-837b0700-3c36-11ea-85d9-a1eef8728083.png)

So the CupertinoButton solution is worse than the Icon solution. CupertinoButton seems to work only correctly if Text is used inside the button. It seems to have problems with icons.

Thus I have reported this problem to the Cupertino project: https://github.com/flutter/flutter/issues/49157

CupertinoButton does not seem to be a good choice for Text, too.

Just with Text:

![Simulator_Screen_Shot_-_iPhone_8_-_2020-01-21_at_10_14_23](https://user-images.githubusercontent.com/17218461/72791080-fedcb880-3c36-11ea-9f36-1667eb7ecc3c.png)

With CupertinoButton with Text and padding 0:

![Simulator_Screen_Shot_-_iPhone_8_-_2020-01-21_at_10_16_07](https://user-images.githubusercontent.com/17218461/72791125-14ea7900-3c37-11ea-95c6-b5994a3017ca.png)

Native iOS 13 app:

![Simulator_Screen_Shot_-_iPhone_8_-_2020-01-21_at_10_24_27](https://user-images.githubusercontent.com/17218461/72791818-43b51f00-3c38-11ea-896f-0ad1f9d90732.png)


So just with "Text" the position and size is better than when using CupertinoButton. One just would have to change the color and would match the native look much better than when using CupertinoButton.

**Comment by aqwert** [comment] 2020-01-21 21:11
Thats ok, As far as the widget used on the app bar whether it be an icon or text is really up to you. 
What it looks like is needed is a specific button that can be used on the app bar whether it be icon or text that will have the right size, padding, color and effects. There is also the consideration of what the padding is when there is more than one button. 

There is no specific app bar button from flutter but there could be a case for putting together a more opinionated widget that meets these requirements.

Is there a link to apples design of the app bar with those buttons, with information as to what the size, padding, color and effects are for a single button and 2 or 3 buttons side by side?

**Comment by dg76** [comment] 2020-01-22 07:56
I think you can find some of that information here:

https://ivomynttinen.com/blog/ios-design-guidelines

The margin seems to be 8px on each side, the font seems to be 17pt with a spacing of -0.41pt.

To see the margin you have to move the mouse over the "The different states of a Nav Bar on iPhone in portrait mode." screenshot.

**Comment by aqwert** [comment] 2020-06-04 23:18
Closing as this is an issue with flutter itself and not this library.

**Closed by aqwert** 2020-06-04 23:18 UTC
